### ISSUE TITLE
Backend API / Frontend API call

### ISSUE THREAD

**Issue by neuPrashant** [Nikankhadka/GroupD-g5#3]
This issue is assigned to be solved by Nikan Khadka. 
Proper calling of API is Missing.

**Comment by Nikankhadka** [comment]
i have resolved the issue there was an error in query now everything is working fine .

the evidence of issue solving is given below
![Screenshot (76)](https://user-images.githubusercontent.com/95460437/162630777-212d1cb9-6078-4a91-a2e4-99fcbfd8417e.png)
![Screenshot (77)](https://user-images.githubusercontent.com/95460437/162630784-3a9ae51e-3412-4457-a478-0b013136efd3.png)
![Screenshot (78)](https://user-images.githubusercontent.com/95460437/162630788-3c98a02e-768e-4f64-a920-aefd1ac78ca3.png)
