### ISSUE TITLE
Sign Up for new User

### ISSUE THREAD

**Issue by Nikankhadka** [Nikankhadka/GroupD-g5#5]
New user cant signup and login to their respective dashboard

**Comment by DebinLuitel** [comment]
I have fixed this issue now new user can sign up and login to thier respective dashboard.
![Screenshot (199)](https://user-images.githubusercontent.com/89472082/168277413-5b1fa832-9ecb-4a03-bec9-454ed3cef041.png)
![Screenshot (200)](https://user-images.githubusercontent.com/89472082/168277424-830ea3dd-ed74-4376-a83f-fd8e0cc7387d.png)
