### ISSUE TITLE
Design alert box 

### ISSUE THREAD

**Issue by Nikankhadka** [Nikankhadka/GroupD-g5#7]
Deisgn alert box so that user is notified on task completion

**Comment by makaikto123** [comment]
The issue has been fixed. I have created a alert modal after the task completion.

**Comment by makaikto123** [comment]
The issue has been fixed. I have created a alert modal after the task completion.

**Comment by prajhub** [comment]
![newalert](https://user-images.githubusercontent.com/84459821/167778003-c03bbe56-6cf8-44ba-8602-add2b132fb42.png)

**Comment by DebinLuitel** [comment]
This is the alert box of the crops category where admin tries to update, delete or post crop.
![alert](https://user-images.githubusercontent.com/89472082/168276725-7fb56fde-289b-44f8-af88-0689429639d4.PNG)
